/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef FrontEndCoordOps_CONSTANTS_H
#define FrontEndCoordOps_CONSTANTS_H

#include "FrontEndCoordOps_types.h"

namespace FrontEndCoordOps {

class FrontEndCoordOpsConstants {
 public:
  FrontEndCoordOpsConstants();

};

extern const FrontEndCoordOpsConstants g_FrontEndCoordOps_constants;

} // namespace

#endif
