// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "FrontEndCoordOps.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::FrontEndCoordOps;

class FrontEndCoordOpsHandler : virtual public FrontEndCoordOpsIf {
 public:
  FrontEndCoordOpsHandler() {
    // Your initialization goes here
  }

  void notifyConnectionClosed(const std::string& serverIP, const std::string& port) {
    // Your implementation goes here
    printf("notifyConnectionClosed\n");
  }

  void markServerInactive(const std::string& serverIP, const std::string& port) {
    // Your implementation goes here
    printf("markServerInactive\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<FrontEndCoordOpsHandler> handler(new FrontEndCoordOpsHandler());
  ::std::shared_ptr<TProcessor> processor(new FrontEndCoordOpsProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

