/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "FrontEndCoordOps_constants.h"

namespace FrontEndCoordOps {

const FrontEndCoordOpsConstants g_FrontEndCoordOps_constants;

FrontEndCoordOpsConstants::FrontEndCoordOpsConstants() {
}

} // namespace

