/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef KvsCoordOps_H
#define KvsCoordOps_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "KvsCoordOps_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class KvsCoordOpsIf {
 public:
  virtual ~KvsCoordOpsIf() {}
  virtual void get(std::string& _return, const std::string& row) = 0;
};

class KvsCoordOpsIfFactory {
 public:
  typedef KvsCoordOpsIf Handler;

  virtual ~KvsCoordOpsIfFactory() {}

  virtual KvsCoordOpsIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(KvsCoordOpsIf* /* handler */) = 0;
  };

class KvsCoordOpsIfSingletonFactory : virtual public KvsCoordOpsIfFactory {
 public:
  KvsCoordOpsIfSingletonFactory(const ::std::shared_ptr<KvsCoordOpsIf>& iface) : iface_(iface) {}
  virtual ~KvsCoordOpsIfSingletonFactory() {}

  virtual KvsCoordOpsIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(KvsCoordOpsIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<KvsCoordOpsIf> iface_;
};

class KvsCoordOpsNull : virtual public KvsCoordOpsIf {
 public:
  virtual ~KvsCoordOpsNull() {}
  void get(std::string& /* _return */, const std::string& /* row */) override {
    return;
  }
};

typedef struct _KvsCoordOps_get_args__isset {
  _KvsCoordOps_get_args__isset() : row(false) {}
  bool row :1;
} _KvsCoordOps_get_args__isset;

class KvsCoordOps_get_args {
 public:

  KvsCoordOps_get_args(const KvsCoordOps_get_args&);
  KvsCoordOps_get_args& operator=(const KvsCoordOps_get_args&);
  KvsCoordOps_get_args() noexcept;

  virtual ~KvsCoordOps_get_args() noexcept;
  std::string row;

  _KvsCoordOps_get_args__isset __isset;

  void __set_row(const std::string& val);

  bool operator == (const KvsCoordOps_get_args & rhs) const;
  bool operator != (const KvsCoordOps_get_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const KvsCoordOps_get_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class KvsCoordOps_get_pargs {
 public:


  virtual ~KvsCoordOps_get_pargs() noexcept;
  const std::string* row;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _KvsCoordOps_get_result__isset {
  _KvsCoordOps_get_result__isset() : success(false) {}
  bool success :1;
} _KvsCoordOps_get_result__isset;

class KvsCoordOps_get_result {
 public:

  KvsCoordOps_get_result(const KvsCoordOps_get_result&);
  KvsCoordOps_get_result& operator=(const KvsCoordOps_get_result&);
  KvsCoordOps_get_result() noexcept;

  virtual ~KvsCoordOps_get_result() noexcept;
  std::string success;

  _KvsCoordOps_get_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const KvsCoordOps_get_result & rhs) const;
  bool operator != (const KvsCoordOps_get_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const KvsCoordOps_get_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _KvsCoordOps_get_presult__isset {
  _KvsCoordOps_get_presult__isset() : success(false) {}
  bool success :1;
} _KvsCoordOps_get_presult__isset;

class KvsCoordOps_get_presult {
 public:


  virtual ~KvsCoordOps_get_presult() noexcept;
  std::string* success;

  _KvsCoordOps_get_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class KvsCoordOpsClient : virtual public KvsCoordOpsIf {
 public:
  KvsCoordOpsClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  KvsCoordOpsClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void get(std::string& _return, const std::string& row) override;
  void send_get(const std::string& row);
  void recv_get(std::string& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class KvsCoordOpsProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<KvsCoordOpsIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (KvsCoordOpsProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_get(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  KvsCoordOpsProcessor(::std::shared_ptr<KvsCoordOpsIf> iface) :
    iface_(iface) {
    processMap_["get"] = &KvsCoordOpsProcessor::process_get;
  }

  virtual ~KvsCoordOpsProcessor() {}
};

class KvsCoordOpsProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  KvsCoordOpsProcessorFactory(const ::std::shared_ptr< KvsCoordOpsIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< KvsCoordOpsIfFactory > handlerFactory_;
};

class KvsCoordOpsMultiface : virtual public KvsCoordOpsIf {
 public:
  KvsCoordOpsMultiface(std::vector<std::shared_ptr<KvsCoordOpsIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~KvsCoordOpsMultiface() {}
 protected:
  std::vector<std::shared_ptr<KvsCoordOpsIf> > ifaces_;
  KvsCoordOpsMultiface() {}
  void add(::std::shared_ptr<KvsCoordOpsIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void get(std::string& _return, const std::string& row) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get(_return, row);
    }
    ifaces_[i]->get(_return, row);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class KvsCoordOpsConcurrentClient : virtual public KvsCoordOpsIf {
 public:
  KvsCoordOpsConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  KvsCoordOpsConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void get(std::string& _return, const std::string& row) override;
  int32_t send_get(const std::string& row);
  void recv_get(std::string& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
