/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "KvsCoordOps_constants.h"



const KvsCoordOpsConstants g_KvsCoordOps_constants;

KvsCoordOpsConstants::KvsCoordOpsConstants() {
}



