/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef KvsCoordOps_CONSTANTS_H
#define KvsCoordOps_CONSTANTS_H

#include "KvsCoordOps_types.h"



class KvsCoordOpsConstants {
 public:
  KvsCoordOpsConstants();

};

extern const KvsCoordOpsConstants g_KvsCoordOps_constants;



#endif
