/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "StorageOps_constants.h"

namespace storage {

const StorageOpsConstants g_StorageOps_constants;

StorageOpsConstants::StorageOpsConstants() {
}

} // namespace

