/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef StorageOps_CONSTANTS_H
#define StorageOps_CONSTANTS_H

#include "StorageOps_types.h"

namespace storage {

class StorageOpsConstants {
 public:
  StorageOpsConstants();

};

extern const StorageOpsConstants g_StorageOps_constants;

} // namespace

#endif
