// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "StorageOps.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::storage;

class StorageOpsHandler : virtual public StorageOpsIf {
 public:
  StorageOpsHandler() {
    // Your initialization goes here
  }

  bool put(const std::string& row, const std::string& col, const std::string& value) {
    // Your implementation goes here
    printf("put\n");
  }

  bool replicateData(const std::string& row, const std::string& col, const std::string& value) {
    // Your implementation goes here
    printf("replicateData\n");
  }

  void get(std::string& _return, const std::string& row, const std::string& col) {
    // Your implementation goes here
    printf("get\n");
  }

  bool deleteCell(const std::string& row, const std::string& col) {
    // Your implementation goes here
    printf("deleteCell\n");
  }

  bool deleteReplicate(const std::string& row, const std::string& col) {
    // Your implementation goes here
    printf("deleteReplicate\n");
  }

  bool cput(const std::string& row, const std::string& col, const std::string& old_value, const std::string& new_value) {
    // Your implementation goes here
    printf("cput\n");
  }

  void sync(std::string& _return, const std::string& which) {
    // Your implementation goes here
    printf("sync\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<StorageOpsHandler> handler(new StorageOpsHandler());
  ::std::shared_ptr<TProcessor> processor(new StorageOpsProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

